spring.datasource.url=jdbc:postgresql://localhost:5432/splitmate
spring.datasource.username= postgres
spring.datasource.password=lion4333

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.thymeleaf.cache=false
springdoc.swagger-ui.path=/swagger-ui.html
